### ISSUE TITLE
Cannot run a local bsc network

### ISSUE THREAD

**Issue by Swain-Xie** [binance-chain/bsc#295] opened 2021-06-17 18:24 UTC
wget  https://github.com/binance-chain/bsc/releases/download/v1.1.0-beta/geth_mac

mkdir ./local

Create this file : ./genesis.json ,there is the link . [here is your guide](https://docs.binance.org/smart-chain/developer/deploy/local.html).
```
{
     "config": {
       "chainId": 1000,
       "homesteadBlock": 0,
       "eip150Block": 0,
       "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
       "eip155Block": 0,
       "eip158Block": 0,
       "byzantiumBlock": 0,
       "constantinopleBlock": 0,
       "petersburgBlock": 0,
       "istanbulBlock": 0,
       "muirGlacierBlock": 0
      },
     "nonce": "0x0000000000000061",
     "timestamp": "0x0",
     "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "gasLimit": "0x8000000",
     "difficulty": "0x100",
     "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
     "coinbase": "0x3333333333333333333333333333333333333333",
     "alloc": {}
}
```

$ geth_mac --datadir ./local/node1 init ./genesis.json
```
xxxxx
xxxx
xxx
xxx
INFO [06-18|02:07:15.303] Successfully wrote genesis state         database=lightchaindata hash=acdfa6..7365e9
```
$ geth --datadir ./local/node1 --networkid 1000 console
```
INFO [06-18|02:08:26.446] Maximum peer count                       ETH=50 LES=0 total=50
INFO [06-18|02:08:26.447] Set global gas cap                       cap=25,000,000
INFO [06-18|02:08:26.447] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [06-18|02:08:26.447] Allocated cache and file handles         database=/Users/xx/bsc-node/local/node1/geth/chaindata cache=512.00MiB handles=5120
INFO [06-18|02:08:26.566] Opened ancient database                  database=/Users/xx/bsc-node/local/node1/geth/chaindata/ancient readonly=false
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 0
```

I followed the guide completely, but I failed to start .

**Comment by guagualvcha** [comment] 2021-07-09 09:23
I am aware of this, will fix it in next release.

**Comment by Gredys** [comment] 2021-07-27 08:22
Release was pushed yesterday but the problem is not solved. Will it be fixed? If yes - when?

**Comment by guagualvcha** [comment] 2021-08-08 07:03
It is fixed in latest release, please verify.

**Closed by guagualvcha** 2021-08-08 07:03 UTC
