### ISSUE TITLE
Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

### ISSUE THREAD

**Issue by aplut** [binance-chain/bsc#276] opened 2021-06-05 18:54 UTC
Hi,

I just built the client using the source code. After downloading genesis.json I run

> /opt/geth/geth --datadir /opt/geth/node init /opt/geth/genesis.json

The output was:

> INFO [06-05|18:49:38.326] Maximum peer count                       ETH=50 LES=0 total=50
> INFO [06-05|18:49:38.326] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
> INFO [06-05|18:49:38.326] Set global gas cap                       cap=25,000,000
> INFO [06-05|18:49:38.326] Allocated cache and file handles         database=/opt/geth/node/geth/chaindata cache=16.00MiB handles=16
> INFO [06-05|18:49:38.528] Writing custom genesis block 
> INFO [06-05|18:49:38.529] Persisted trie from memory database      nodes=15 size=2.32KiB time="94.611µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
> INFO [06-05|18:49:38.529] Successfully wrote genesis state         database=chaindata                     hash=0d2184..d57b5b
> INFO [06-05|18:49:38.529] Allocated cache and file handles         database=/opt/geth/node/geth/lightchaindata cache=16.00MiB handles=16
> INFO [06-05|18:49:38.670] Writing custom genesis block 
> INFO [06-05|18:49:38.672] Persisted trie from memory database      nodes=15 size=2.32KiB time="142.135µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
> INFO [06-05|18:49:38.673] Successfully wrote genesis state         database=lightchaindata    

I tried several time to run the client using:

> /opt/geth/geth --config /opt/geth/config.toml --datadir /otp/geth/node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --ws

But always with the same result:

> Fatal: Failed to register the Ethereum service: unsupported fork ordering: mirrorSyncBlock not enabled, but berlinBlock enabled at 12244000

For me it looks like that it tries to connect to Eth mainnet instead of BSC, but looking into /opt/geth/config.toml I see:

> [Eth]
> NetworkId = 56

My client version:

> Geth
> Version: 1.1.0-beta
> Git Commit: b67a129e5bdd2774c9493f505d1a83f1e0a215c4
> Git Commit Date: 20210524
> Architecture: amd64
> Go Version: go1.16.5
> Operating System: linux
> GOPATH=
> GOROOT=go

Do you have any idea what can be wrong?

Best,
Adrian

**Comment by Zaczero** [comment] 2021-06-05 21:19
Those are my steps I have just followed and I couldn't reproduce your issue.
1. Download geth client (geth_linux or geth_mac from releases)
2. Download mainnet.zip (also from releases)
3. Unpack everything to the same directory and cd into it
4. Make geth executable with: chmod +x geth
5. Initialize the node with: ./geth --datadir ./node init ./genesis.json
6. Start the node with: ./geth --config ./config.toml --datadir ./node

**Comment by koen84** [comment] 2021-06-07 13:38
You did your init / startup wrong, you're trying to sync ETH mainnet rather than BSC.

**Comment by koen84** [comment] 2021-06-07 13:40
Correct this part of your startup `--datadir /otp/geth/node`

**Comment by mmotiy** [comment] 2021-06-28 09:59
I am faced with the same problem

**Comment by sorokousov** [comment] 2021-06-29 15:08
I have the same problem. Why did you make it so difficult?

**Comment by vaclandic** [comment] 2021-07-05 09:06
Same problem with v1.1.0-beta, when start new node
Is there any information about this issue?

**Comment by happysammy** [comment] 2021-07-12 02:02
I also have the same problem.

**Comment by SatanBtc** [comment] 2021-07-17 11:35
the same 。。how to fix？

**Comment by shelldor73** [comment] 2021-07-29 15:26
same problem, is there any solution ?

**Comment by hoyang** [comment] 2021-08-09 09:30
same problem, is there any solution?

**Comment by guagualvcha** [comment] 2021-11-30 04:15
Will kindly close this,  works fine in the latest release.

**Closed by guagualvcha** 2021-11-30 04:15 UTC
