### ISSUE TITLE
Handle Request Error

### ISSUE THREAD

**Issue by Wetitpig** [binance-chain/bsc#147] opened 2021-04-14 14:02 UTC
I have tried the community nodes mentioned in [this page](https://docs.binance.org/smart-chain/developer/rpc.html).
However, when I send requests to the nodes, they return the error:
```
{"id":0,"jsonrpc":"2.0","error":{"code":-32603,"message":"handle request error"}}
```

I am not sure if this is the right place to ask, but I could not find anywhere else covering this issue. Could anyone explain why this would happen if they are also implementing this version of bsc client? Thank you very much!

**Comment by guagualvcha** [comment] 2021-04-16 02:34
Hi, can you pasted your request here, this error usually caused by heavy request and timeout, the timeout setting is 5 second

**Comment by Wetitpig** [comment] 2021-04-17 05:22
The case seems to be intermittent and could be due to timeout (I send requests in batch to avoid too many individual calls.) Maybe it would be better to respond with an error like
```
{"id":0,"jsonrpc":"2.0","error":{"code":-32603,"message":"execution timeout (timeout=5s)"}}
```

**Comment by guagualvcha** [comment] 2021-11-29 10:32
@Wetitpig noted, but since the change is not on bsc, but on a proxy program, so I will close this.

**Closed by guagualvcha** 2021-11-29 10:32 UTC
