### ISSUE TITLE
fast node in Rpi 8 GB

### ISSUE THREAD

**Issue by soltrac** [binance-chain/bsc#126] opened 2021-03-26 09:26 UTC
Hi there,

Just to know, has someone has been able to sync a full node on the last Rpi with a fast SSD external USB 3.0? I know that in ethereum is possible, but BSC is much faster and I would like to know first if someone has been able to do it.

Thanks.

**Comment by dsbaars** [comment] 2021-03-28 00:24
Although BSC is "faster" in some aspects, the 3 seconds block time makes it hard to keep up even with an NVMe SSD on a Ryzen 2600X with 16GB RAM. The first fast sync is okay, but I needed to restart. Now i'm 33 minutes and moving further and further away from the latest block.

**Comment by havsar** [comment] 2021-04-15 13:54
The issue is that the syncing is switching to full as soon as the initial sync is done (as far as I could observe).

**Comment by manelio** [comment] 2021-04-17 12:59
I don't know what's happening. One month ago I was able to fast sync a full node from scratch in 2-3 days on a RPI 8GB / SSD USB3. After a power outage I could not get synced anymore.

My last attempt was with a snapshot of 2021-04-15 (2 days old) but  the progress is being extremely slow. The lack of metrics and estimations of the ETA is frustrating. Mainly the fact of I even don't know if I will be able to get in sync. Two days? One year? Never?

When I got to any result I'll publish here as an issue to share with you all my use case: RPI 8GB/USB3 SSD, {current_date}, snapshot {date}, time to sync: X.  It would be good  to gather information about different use cases.

**Comment by manelio** [comment] 2021-04-17 18:07
Ok. Update.

I gave up again.

After several hours the process was "killed". I'm using a swap of 4 GB.

At this moment all I can say is there's no reliable way to get a BSC node working with a RPI4/SSD USB3.

I'll try alternatives like superior hardware or third party paid services.

**Comment by thomasd3** [comment] 2021-04-21 21:23
is the issue the write speed to the disk? I was considering to do something similar.

**Comment by j75689** [comment] 2021-07-30 09:21
I think using Raspberry Pi to run bsc is not a good choice.
BSC consumes a lot of cpu, memory and disk I/O.

Sorry, I don't know much about Raspberry Pi. Maybe there is already a Raspberry Pi with powerful hardware?

If anyone succeeds, please share here.

**Comment by guagualvcha** [comment] 2021-12-03 02:20
Will kindly close this issue, seems many guys give the answers. Thanks

**Closed by guagualvcha** 2021-12-03 02:20 UTC
Labels: question
